baseURL = "https://purpleidea.com/"
languageCode = "en-ca"
title = "purpleidea.com"

pygmentsCodeFences = true

[author]
  name = "James Shubin"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  github = "https://github.com/purpleidea/"
  twitter = "https://twitter.com/purpleidea"
  publickeyfile = "static/james@shubin.ca.asc"

  # https://api.staticman.net/v2/entry/{GITHUB USERNAME}/{GITHUB REPOSITORY}/{BRANCH}/{PROPERTY (optional)}
  staticmanURL = "https://api.staticman.net/v2/entry/purpleidea/purpleidea.com/master"
  staticmanPR = "https://github.com/purpleidea/purpleidea.com/pulls"
